# Generated by Django 2.1.3 on 2018-11-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_ghomeentry_testentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghomeentry',
            name='read_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testentry',
            name='read_num',
            field=models.IntegerField(),
        ),
    ]
