# Generated by Django 2.1.3 on 2018-11-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_auto_20181129_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subContent',
            field=models.TextField(default='', verbose_name='副文本'),
        ),
    ]
