# Generated by Django 2.1.3 on 2018-11-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_blog_subcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subContent',
            field=models.TextField(verbose_name='副文本'),
        ),
    ]
